# Generated by Django 5.1.4 on 2024-12-14 08:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('device_name', models.CharField(max_length=200)),
                ('ip_address', models.GenericIPAddressField()),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SharedFile',
        ),
    ]
